# Generated by Django 5.2.8 on 2025-11-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otm_name', models.CharField(max_length=100)),
                ('otm_email', models.EmailField(max_length=254)),
                ('otm_phone_number', models.CharField(max_length=20)),
                ('otm_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_field', models.CharField(max_length=100)),
                ('otm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.otm')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_f_name', models.CharField(max_length=50)),
                ('student_l_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone_number', models.CharField(max_length=20)),
                ('student_birth_year', models.IntegerField()),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.group')),
            ],
        ),
    ]
